### PR TITLE
add MUX fees adapter

### PR DESCRIPTION
**Pull request by xionyk**
revenue:
fee × 70% × POR: Allocate for veMUX holders (in ETH)
fee × 30%: Purchase MUXLP and add as protocol-owned liquidity
POR is the rate of [Protocol Owned Liquidity](https://github.com/protocol/liquidity#protocol-owned-liquidity)

Here is the test results:
🦙 Running MUX adapter 🦙
_______________________________________
Fees for 28/10/2022
_______________________________________

ARBITRUM 👇
Backfill start time: 1/8/2022
Timestamp: 1666915199
Total fees: 0
Daily fees: 35089.84287823406
Total revenue: 0
Daily revenue: 28102.765039470443

BSC 👇
Backfill start time: 1/8/2022
Timestamp: 1666915199
Total fees: 0
Daily fees: 175.16929680025882
Total revenue: 0
Daily revenue: 140.28964470400837

AVAX 👇
Backfill start time: 1/8/2022
Timestamp: 1666915199
Total fees: 0
Daily fees: 1214.0303679698818
Total revenue: 0
Daily revenue: 972.2930450339036

FANTOM 👇
Backfill start time: 1/8/2022
Timestamp: 1666915199
Total fees: 0
Daily fees: 209.50287902086188
Total revenue: 0
Daily revenue: 167.786735456371

### CODE REVIEW

**Comment by llamatester** [comment]
The mux.ts adapter exports: 
        
 
 _______________________________________
    Fees for 2/11/2022
    _______________________________________
    
    ARBITRUM 👇
    Timestamp attempted: 1/11/2022
    TypeError: Cannot read properties of undefined (reading 'rows')
        at /home/runner/work/adapters/adapters/fees/mux.ts:47:57
        at processTicksAndRejections (node:internal/process/task_queues:96:5)
        at async /home/runner/work/adapters/adapters/adapters/utils/runAdapter.ts:30:52
    
    
    BSC 👇
    Timestamp attempted: 1/11/2022
    TypeError: Cannot read properties of undefined (reading 'rows')
        at /home/runner/work/adapters/adapters/fees/mux.ts:47:57
        at processTicksAndRejections (node:internal/process/task_queues:96:5)
        at async /home/runner/work/adapters/adapters/adapters/utils/runAdapter.ts:30:52
    
    
    AVAX 👇
    Timestamp attempted: 1/11/2022
    TypeError: Cannot read properties of undefined (reading 'rows')
        at /home/runner/work/adapters/adapters/fees/mux.ts:47:57
        at processTicksAndRejections (node:internal/process/task_queues:96:5)
        at async /home/runner/work/adapters/adapters/adapters/utils/runAdapter.ts:30:52
    
    
    FANTOM 👇
    Timestamp attempted: 1/11/2022
    TypeError: Cannot read properties of undefined (reading 'rows')
        at /home/runner/work/adapters/adapters/fees/mux.ts:47:57
        at processTicksAndRejections (node:internal/process/task_queues:96:5)
        at async /home/runner/work/adapters/adapters/adapters/utils/runAdapter.ts:30:52
    
    
    
    
    Done in 7.70s.

**Comment by 0xngmi** [comment]
could you fix the CI errors pls?

**Comment by xionyk** [comment]
We'll fix it as soon as possible

**Comment by xionyk** [comment]
Please try to run it again. If there are still errors, we will check if there is a problem with our api.

**Comment by llamatester** [comment]
The mux.ts adapter exports: 
        
 
 _______________________________________
    Fees for 7/11/2022
    _______________________________________
    
    ARBITRUM 👇
    Backfill start time: 1/8/2022
    Timestamp: 1667865598
    Total fees: 0
    Daily fees: 17546.484798068785
    Total revenue: 0
    Daily revenue: 13829.588917944764
    
    
    BSC 👇
    Backfill start time: 1/8/2022
    Timestamp: 1667865598
    Total fees: 0
    Daily fees: 347.8473030706618
    Total revenue: 0
    Daily revenue: 274.1623329712436
    
    
    AVAX 👇
    Backfill start time: 1/8/2022
    Timestamp: 1667865598
    Total fees: 0
    Daily fees: 780.6853742495326
    Total revenue: 0
    Daily revenue: 615.3117233664486
    
    
    FANTOM 👇
    Backfill start time: 1/8/2022
    Timestamp: 1667865598
    Total fees: 0
    Daily fees: 5.67008782674639
    Total revenue: 0
    Daily revenue: 4.468985365158494
    
    
    
    
    Done in 5.61s.

**Pull request merged**
