### PR TITLE
Add dex and fees for emdx

### PR DESCRIPTION
**Pull request by afiorenza**

### CODE REVIEW

**Comment by afiorenza** [comment]
> hi, could you remove change `package-lock` and `yarn.lock` in this pr

Done! Thanks for reviewing

**Comment by llamatester** [comment]
The emdx adapter exports: 
        
 
 _______________________________________
    Dexs for 18/11/2022
    _______________________________________
    
    AVAX 👇
    Backfill start time: 20/5/2022
    Timestamp: 1668729600
    Daily volume: 938772.6511062841
    Total volume: 386549898.69963604
    
    
    
    
    Done in 3.50s.

**Comment by llamatester** [comment]
The emdx.ts adapter exports: 
        
 
 _______________________________________
    Fees for 18/11/2022
    _______________________________________
    
    AVAX 👇
    Backfill start time: 20/5/2022
    Timestamp: 1668815998
    Total fees: 383458.4799445226
    Daily fees: 994.921620837466
    Total revenue: 0
    Daily revenue: 0
    
    
    
    
    Done in 3.37s.

**Comment by dtmkeng** [comment]
@afiorenza hi seems like your adapter returned the same data  for any DateTime, could you check this

**Pull request merged**
